apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service-deployment
  labels:
    app: tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-container
          image: danijelsudimac/tracking-service:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_DATASOURCE_URL_2
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_DATASOURCE_URL_2
            - name: SPRING_DATASOURCE_USERNAME_2
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_DATASOURCE_USERNAME_2
            - name: SPRING_DATASOURCE_PASSWORD_2
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_DATASOURCE_PASSWORD_2
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_KAFKA_API_KEY
            - name: SPRING_KAFKA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_KAFKA_API_SECRET
            - name: SPRING_SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_SCHEMA_REGISTRY_URL
            - name: SPRING_SCHEMA_REGISTRY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_SCHEMA_REGISTRY_API_KEY
            - name: SPRING_SCHEMA_REGISTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: shipment-platform-secrets
                  key: SPRING_SCHEMA_REGISTRY_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  type: ClusterIP
  selector:
    app: tracking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

